[2022-12-13 22:39:38,320][FLSim.builder][INFO] - benchmark.ctx.synthetic has created !
[2022-12-13 22:39:38,333][FLSim.builder][INFO] - benchmark.model.leaf.SyntheticMLP has created !
[2022-12-13 22:40:47,379][FLSim.FedClusterNone][INFO] - cluster result: [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 2 2 2 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[2022-12-13 22:40:47,404][FLSim.builder][INFO] - trainer.algorithm.cfl.fedcluster.FedCluster has created !
[2022-12-13 22:40:47,404][FLSim.FedClusterNone][INFO] - FedClusterNone Start training ......
[2022-12-13 22:40:47,404][FLSim.FedClusterNone][INFO] - [0] Selected: ['f_00023', 'f_00030', 'f_00022', 'f_00078', 'f_00079', 'f_00025', 'f_00015', 'f_00013', 'f_00087', 'f_00089', 'f_00064', 'f_00052']
[2022-12-13 22:40:47,404][FLSim.__main__][DEBUG] - Traceback (most recent call last):
  File "D:\Project\Python\flsim\benchmark\starter.py", line 28, in run
    trainer.start()
  File "D:\Project\Python\flsim\trainer\core\proto.py", line 183, in start
    self._local_update(selected)
  File "D:\Project\Python\flsim\trainer\core\proto.py", line 151, in _local_update
    for cid, res in zip(cids, self._pool.map(lambda a, v: a.fit.remote(*v), self._local_update_setup(cids))):
  File "D:\Project\Python\flsim\trainer\core\proto.py", line 148, in _local_update_setup
    return [(self._state(c), self._fds.train(c), args) for c in cids]
  File "D:\Project\Python\flsim\trainer\core\proto.py", line 148, in <listcomp>
    return [(self._state(c), self._fds.train(c), args) for c in cids]
TypeError: 'collections.OrderedDict' object is not callable

